name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  equatable: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  intl: 0.19.0
  meta: ^1.11.0
  shared_preferences: ^2.0.5
  geolocator: ^10.1.0
  permission_handler_android: ^10.3.6
  permission_handler: ^10.4.5
  nimble_charts: ^0.5.0-beta
  flutter_swiper_null_safety: ^1.0.2
  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
      - family: WeatherIcons  
        fonts:
          - asset: assets/fonts/weathericons-regular-webfont.ttf