name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # 添加這個 permissions 塊
      contents: read
      pages: write # 授予 pages 寫入權限，用於部署
      id-token: write # 授予 id-token 寫入權限，解決當前錯誤

    defaults:
      run:
        working-directory: flutter_application_1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web with base href
        run: flutter build web --release --base-href="/SelfUsedWeatherAppTest/"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # 確保這裡是 v3
        with:
          path: flutter_application_1/build/web/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # 確保這裡還是 v4 (actions/deploy-pages@v4 是正確的)
